### ISSUE TITLE
How to understand different lengths of diverging lineages within a trajectory?

### ISSUE THREAD

**Issue by Sophia409** [statOmics/tradeSeq#181] opened 2022-01-09 07:26 UTC
Hi, all
My data contains 3 lineages that share a common initial state but branch and terminate at different clusters (2, 4, 5). Among these branching lineages, lineage 3 ends at pseudotime value 30. But lineage 1 and 2 reach to pseudotime value 40. Why lineage 3 ends so early? How to understand different lengths of pseudotime across lineages? Does it mean that cells in lineage 3 reach to the terminal state at earlier time, then become static, while other lineages are still differentiating? It seems weird.
 
![图片](https://user-images.githubusercontent.com/30619010/148673189-8ebba6d6-4e73-48d7-88e6-8e311471b734.png)

After I checked the real time identities of these clusters, I found that cluster 2 in lineage3 contains more cells at early stage while cluster 4 and 5 in other lineages contain more cells at late stage. Even so, cluster 2 covered cells at all stages. It means that cells in cluster2 still exist at late stage. This is inconsistent with the slingshot result that they disappear at later time.
 
![图片](https://user-images.githubusercontent.com/30619010/148673192-508f7881-3a56-4af9-b43f-e6496b48e242.png)

Could you help me figure it out here? Would be greatly appreciated!

Best regards and many thanks!
Sophia

**Comment by kstreet13** [comment] 2022-01-10 15:10
Duplicate of https://github.com/kstreet13/slingshot/issues/169.
Responding there because this seems like more of a Slingshot issue.

**Closed by kstreet13** 2022-01-10 15:10 UTC
