### ISSUE TITLE
plotSmoothers - flipped lineage line and point colours?

### ISSUE THREAD

**Issue by kmshort** [statOmics/tradeSeq#116] opened 2021-02-01 00:35 UTC
Hi,

Using plotSmoothers, I've noticed that the colouration is being mixed up between the points and the lineage lines.

![Six3_NPD_LPD](https://user-images.githubusercontent.com/7980275/106402312-073c1600-647d-11eb-96a1-9ca39c00eb7e.png)

Lineage1 is purple and Lineage2 is yellow, and likewise for the cell points.
I know the cells of Lineage2 (NPD) don't express that gene, which can be seen with Seurat FeaturePlot:
![Six3_NPD_LPD_fp](https://user-images.githubusercontent.com/7980275/106402874-d7424200-647f-11eb-8ba4-026ae4d7ec96.png)
It also shows that there are a lot of NPD cells totally absent at the end of pseudotime, and that's also the area where Six3 expression is strong, you can see this using plotGeneCount:
![Six3_NPD_LPD_gc](https://user-images.githubusercontent.com/7980275/106402892-f0e38980-647f-11eb-8890-e46add1acbfe.png)

So, there are no points for Lineage 2 NPD cells toward the end of pseudotime in the plotSmoothers output. Yet, the Lineage2 yellow curve is high and increases toward the end of pseudotime, even when there are no cells. 

Meanwhile, Lineage 1 is flat at 0 for the entirety of pseudotime in plotSmoothers. Furthermore, it ends prematurely at ~pesudotime 18 or so. This is exactly what I would expect Lineage 2 to do.
Yes, expression would be expected to also be 0 in LPD for much of peudotime (look at the FeaturePlot), but increases significantly towards the end, right to the very end of pesudotime.

![Six3_NPD_LPD](https://user-images.githubusercontent.com/7980275/106402312-073c1600-647d-11eb-96a1-9ca39c00eb7e.png)

So my conclusion is that the colours of either the lineage line (or the points) seems flipped around.
Why would this be? How can I fix it?

It is only in this clear-cut case that I've seen it, but perhaps it happens every time in plotSmoothers (and it is with my prior knowledge of this behaviour that has led me to find it). So I wonder if this is a problem for all my usages of plotSmoothers where the differences in gene expression are not so clear cut?
It makes me worry.

I hope you can help!
thanks

**Comment by HectorRDB** [comment] 2021-02-01 05:30
Hi @kmshort 
Thanks for noticing this, it is indeed quite strange. I did not notice this behavior before. Could you please share the exact command you used to run plotSmoothers?

**Comment by kmshort** [comment] 2021-02-01 05:54
Hi @HectorRDB,

`plotSmoothers(seurat_sce_ss_UMAP_ts, e14_counts, gene = "Six3", alpha = 0.1) + ggtitle("Six3")`

**Comment by HectorRDB** [comment] 2021-02-01 06:29
Hi,
Thanks for this.  Can you just confirm that you have the latest version of tradeSeq installed?

**Comment by kmshort** [comment] 2021-02-01 06:37
Hi @HectorRDB ,

I'm running:
`tradeSeq_1.4.0`
as reported by sessionInfo()

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8      
 [8] LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gridExtra_2.3                 WebGestaltR_0.4.4             limma_3.46.0                  org.Mm.eg.db_3.12.0           AnnotationDbi_1.52.0         
 [6] msigdbr_7.2.1                 pheatmap_1.0.12               UpSetR_1.4.0                  RColorBrewer_1.1-2            bioc2020trajectories_0.0.0.93
[11] tradeSeq_1.4.0                dplyr_1.0.2                   ggdark_0.2.1                  ggthemes_4.2.0                ggbeeswarm_0.6.0             
[16] ggplot2_3.3.2                 SummarizedExperiment_1.20.0   Biobase_2.50.0                GenomicRanges_1.42.0          GenomeInfoDb_1.26.2          
[21] IRanges_2.24.1                S4Vectors_0.28.1              BiocGenerics_0.36.0           MatrixGenerics_1.2.0          matrixStats_0.57.0           
[26] slingshot_1.8.0               princurve_2.1.5               Seurat_3.2.3                 

loaded via a namespace (and not attached):
  [1] reticulate_1.18             tidyselect_1.1.0            RSQLite_2.2.1               htmlwidgets_1.5.3           combinat_0.0-8             
  [6] docopt_0.7.1                BiocParallel_1.24.1         Rtsne_0.15                  munsell_0.5.0               codetools_0.2-18           
 [11] ica_1.0-2                   future_1.21.0               miniUI_0.1.1.1              withr_2.3.0                 colorspace_2.0-0           
 [16] fastICA_1.2-2               knitr_1.30                  rstudioapi_0.13             SingleCellExperiment_1.12.0 ROCR_1.0-11                
 [21] tensor_1.5                  listenv_0.8.0               labeling_0.4.2              slam_0.1-48                 GenomeInfoDbData_1.2.4     
 [26] polyclip_1.10-0             farver_2.0.3                bit64_4.0.5                 rhdf5_2.34.0                parallelly_1.22.0          
 [31] vctrs_0.3.6                 generics_0.1.0              xfun_0.19                   BiocFileCache_1.14.0        R6_2.5.0                   
 [36] doParallel_1.0.16           rsvd_1.0.3                  VGAM_1.1-4                  locfit_1.5-9.4              bitops_1.0-6               
 [41] rhdf5filters_1.2.0          spatstat.utils_1.17-0       DelayedArray_0.16.0         assertthat_0.2.1            promises_1.1.1             
 [46] scales_1.1.1                beeswarm_0.2.3              gtable_0.3.0                globals_0.14.0              goftest_1.2-2              
 [51] rlang_0.4.9                 systemfonts_0.3.2           splines_4.0.3               lazyeval_0.2.2              yaml_2.2.1                 
 [56] reshape2_1.4.4              abind_1.4-5                 httpuv_1.5.4                tools_4.0.3                 ellipsis_0.3.1             
 [61] ggridges_0.5.2              Rcpp_1.0.5                  plyr_1.8.6                  zlibbioc_1.36.0             purrr_0.3.4                
 [66] RCurl_1.98-1.2              densityClust_0.3            rpart_4.1-15                deldir_0.2-3                pbapply_1.4-3              
 [71] viridis_0.5.1               cowplot_1.1.0               zoo_1.8-8                   ggrepel_0.9.0               cluster_2.1.0              
 [76] tinytex_0.28                apcluster_1.4.8             magrittr_2.0.1              RSpectra_0.16-0             data.table_1.13.4          
 [81] scattermore_0.7             lmtest_0.9-38               RANN_2.6.1                  whisker_0.4                 fitdistrplus_1.1-3         
 [86] hms_0.5.3                   patchwork_1.1.1             mime_0.9                    evaluate_0.14               xtable_1.8-4               
 [91] sparsesvd_0.2               HSMMSingleCell_1.10.0       compiler_4.0.3              tibble_3.0.4                KernSmooth_2.23-18         
 [96] crayon_1.3.4                htmltools_0.5.0             mgcv_1.8-33                 later_1.1.0.1               tidyr_1.1.2                
[101] DBI_1.1.0                   dbplyr_2.0.0                MASS_7.3-53                 rappdirs_0.3.1              readr_1.4.0                
[106] Matrix_1.2-18               igraph_1.2.6                forcats_0.5.0               pkgconfig_2.0.3             plotly_4.9.2.2             
[111] foreach_1.5.1               svglite_1.2.3.2             vipor_0.4.5                 rngtools_1.5                XVector_0.30.0             
[116] doRNG_1.8.2                 stringr_1.4.0               digest_0.6.27               sctransform_0.3.2           RcppAnnoy_0.0.18           
[121] DDRTree_0.1.5               spatstat.data_1.7-0         rmarkdown_2.6               leiden_0.3.6                uwot_0.1.10                
[126] edgeR_3.32.0                gdtools_0.2.2               curl_4.3                    shiny_1.5.0                 lifecycle_0.2.0            
[131] monocle_2.18.0              nlme_3.1-151                jsonlite_1.7.2              Rhdf5lib_1.12.0             viridisLite_0.3.0          
[136] pillar_1.4.7                lattice_0.20-41             GO.db_3.12.1                fastmap_1.0.1               httr_1.4.2                 
[141] survival_3.2-7              glue_1.4.2                  qlcMatrix_0.9.7             FNN_1.1.3                   spatstat_1.64-1            
[146] png_0.1-7                   iterators_1.0.13            bit_4.0.4                   stringi_1.5.3               HDF5Array_1.18.0           
[151] blob_1.2.1                  memoise_1.1.0               irlba_2.3.3                 future.apply_1.6.0          ape_5.4-1  
```

**Comment by HectorRDB** [comment] 2021-02-02 00:48
Hi @kmshort 
Can you please update to the latest tradeSeq version from github. Thanks

**Comment by kmshort** [comment] 2021-02-02 02:20
Hi @HectorRDB 

I've upgraded:

```
packageVersion("tradeSeq")
[1] ‘1.5.5’
```

and the behavior is the same:

![Six3_NPD_LPD_ps_ts1 55](https://user-images.githubusercontent.com/7980275/106543151-493a8a00-6559-11eb-968d-b94080ddfd08.png)

**Comment by HectorRDB** [comment] 2021-02-02 04:25
Ok. I cannot reproduce the error. 
Could you email me the tradeSeq output and count matrix so that I can investigate? Thanks
hector dot rouxdebezieux at berkeley dot edu

**Comment by kmshort** [comment] 2021-02-02 07:10
Hi Hector,

I have sent you the two files.

thanks

**Comment by HectorRDB** [comment] 2021-02-02 16:44
Thanks I received them and I have the same bug on my machine. I will investigate then

**Comment by HectorRDB** [comment] 2021-02-02 17:02
Got it!! It was linked to some weird ordering of the condition vector. Thanks for spotting this!!! 
It should be fixed now if you re-install the very latest tradeSeq version from tradeSeq. 
Best

**Comment by kmshort** [comment] 2021-02-02 22:12
HI @HectorRDB ,

Many thanks, it's working properly now in my hands as well.

```
packageVersion("tradeSeq")
[1] ‘1.5.6’
```

best regards

**Comment by HectorRDB** [comment] 2021-02-02 22:18
It is possible but  it would only happen if the levels of the condition did not match the alphabetical order, which is why we never spotted it. Note also that this was only for plotting, not any other functions.
Best,

**Closed by HectorRDB** 2021-02-02 22:18 UTC
