### ISSUE TITLE
cellWeights are 0/1

### ISSUE THREAD

**Issue by kathrynbowles** [statOmics/tradeSeq#40] opened 2020-04-16 18:54 UTC
Hello, 

I'm looking forward to testing this package - I have a similar goal as in issue #19, and was planning to calculate separate trajectories for Mutant  and wildtype cells - I can see in Monocle3 that several gene trajectories are different between the genotype, but there's no way of quantifying it. Hopefully your package will help with that!

I am running into a problem with the fitGAM preparation from a Monocle CDS. I was able to find what I believe are the root nodes from the Monocle3 shiny interface using: 

root <- cds@principal_graph_aux$UMAP$root_pr_nodes 

(which may be helpful for #38), and otherwise I have followed your vignette exactly. However when I calculate the cellWeights, I am getting a binary data frame of 0s and 1s. When I try to make the sce object using fitGAM, I get the following error: 

Error in .assignCells(cellWeights) : 
  Some cells have no positive cell weights.

I understand this is because my cellWeights is largely populated by 0s, but I'm not sure how I'm ending up with the wrong weights. Do you have any suggestions for what could be happening? 

Thank you,

**Comment by HectorRDB** [comment] 2020-04-16 19:02
Hi @kathrynbowles ,
We are actually working on a major overall of tradeSeq that will help make testing between conditions much easier. If you are interested, you can look at the condition branch of tradeSeq, which already contains more functionalities (tagging @koenvandenberge as well). 

As for the error itself.
It is expected that you get a matrix of zeros and one (monocle3 does hard lineage assignemnts). However, each cell (i.e each row of the data.frame) should have at least one 1. 
That's likely not the case here. That might be because the graph is not fully connected. If you are working on multiple trajectories (i.e you have multiple starting points), then I suggest analyzing each trajectory separately. 

Let me know if that helps,
Best,

**Comment by kathrynbowles** [comment] 2020-04-16 19:18
Thank you for your quick response! 

My graph appears to be fully connected and I am working with a single starting point, although it's quite complex with numerous branches. Could the branching be the issue?

Thanks again,

**Comment by HectorRDB** [comment] 2020-04-16 20:09
No worries. 
I don't think the branching is the issue but could you check where the cells with only zeros are in the trajectory?  If they are located in a specific region, we might be zeroing in on the problem.

Also, can you tell me if, after running this
```
mst <- principal_graph(cds)$UMAP
endpoints <- names(which(igraph::degree(mst) == 1))
```
you find as many endpoints as you are supposed to (i.e all branches + 1 for the root)?

**Comment by kathrynbowles** [comment] 2020-04-16 20:59
They seem pretty randomly distributed to me - there are no particular clusters or nodes enriched for only zero cells - there are 9327 cells out of 161687 that have all 0s. Would it be best to just exclude these particular cells from the analyis?

And yes. I get the right number of endpoints after running that command

**Comment by Seandelao** [comment] 2020-04-17 06:07
Thank you for that bit of code, @kathrynbowles! It allowed me to define a 'root'. 

@HectorRDB after using that, I am also getting the same error:

Error in .assignCells(cellWeights) :
Some cells have no positive cell weights

When looking at the matrix, I see that quite a few cells contain all zeros

**Comment by HectorRDB** [comment] 2020-04-17 10:09
Hi @Seandelao @kathrynbowles 
Thank you to you both for helping me figure this out. I went back and made a few adjustments to the monocle vignette, incorporating the ligne 
```
root <-cds@principal_graph_aux$UMAP$root_pr_nodes
```

The rest of the code had some cosmetic changes but should not have fixed your issues unfortunately. 
What is - i think - happening is in that portion of the code
```
cellWeights <- lapply(endpoints, function(endpoint) {
  # We find the path between the endpoint and the root
  path <- igraph::shortest_paths(mst, root, endpoint)$vpath[[1]]
  path <- as.character(path)
  # We find the cells that map along that path
  df <- y_to_cells %>%
    dplyr::filter(Y %in% path)
  df <- data.frame(weights = as.numeric(colnames(cds) %in% df$cells))
  colnames(df) <- endpoint
  return(df)
  }) 
```

Some nodes (and by extension some cells linked to those nodes) are not being picked up in the shortest paths. Can you check if that is the case (you should be able to see which endpoint-related path they should be on based on their emplacement). 
Would it be possible for you to send the output from `plot_cells(cds, color_cells_by = "pseudotime")`. Thanks

**Comment by Seandelao** [comment] 2020-04-17 16:49
Hi @HectorRDB here is my pseudotime plot. 

Interestingly, after tweaking some of the parameters (number of dims used for dimensional reduction) I am no longer getting the error reported above when running the fitGAM function (haven't finished running it yet though). I am still interested in finding out what was happening though, since I would like to use tradSeq on many different cds objects :)

[pseudotime.pdf](https://github.com/statOmics/tradeSeq/files/4494182/pseudotime.pdf)

**Comment by HectorRDB** [comment] 2020-04-17 16:52
Hi @Seandelao 
Thanks for the plot. Just for clarification, is that the plot where fitGAM is working or the plot from before?

**Comment by Seandelao** [comment] 2020-04-17 16:56
@HectorRDB This the plot where fitGAM is working. I will try to reproduce my previous object where I had the error and post the plot here. 

Side question, when making my cds object for Monocle3 analysis I use non-normalized counts from a Seurat oject which then get processed and normalized via the preprocess() function in Monocle3. When running fitGAM, should I use those same non-normalized counts, or should I use the log normalized counts from the Seurat object/Monocle3 object?

**Comment by Seandelao** [comment] 2020-04-17 17:09
@HectorRDB here is a plot in which the fitGAM function did not work. 

[pseudotime no + cell weights.pdf](https://github.com/statOmics/tradeSeq/files/4494300/pseudotime.no.%2B.cell.weights.pdf)

**Comment by HectorRDB** [comment] 2020-04-17 17:47
Thanks @Seandelao. 
The error comes because you have loops in the trajectory so some nodes are not in the shortest path between the root and endpoints. 
Biological context would help but just judging from the UMAP plot, it looks like you have two clear lineages. I would discard the rest as artifacts if you don't have other relevant information. 

@kathrynbowles  Does your trajectory also includes loops?

**Comment by kathrynbowles** [comment] 2020-04-17 20:21
Hi @HectorRDB 

My trajectories are pretty complex, and yes it looks like there is some looping (image attached). I have a subset of the data that doesn't appear to have loops in the trajectory, so I'll test that and see if I get the same issue

![Picture1](https://user-images.githubusercontent.com/54607872/79610804-3e486300-80c7-11ea-9141-c4ec9e194df7.png)

**Comment by kathrynbowles** [comment] 2020-04-17 20:27
No luck I'm afraid - I just tried on the below data, which doesn't appear to have loops, but I get the same error. 

![pt](https://user-images.githubusercontent.com/54607872/79611328-58367580-80c8-11ea-8ca3-fa002b7c2185.png)

**Comment by HectorRDB** [comment] 2020-04-17 20:44
Hi @kathrynbowles 
Thanks for sharing those images. The plots above do have a couple of loops though (one on the bottom left portion and one in the middle section).
If you want to keep with loops, you can still use tradeSeq but you will have to decide how to interpret loops in that context. 
If you have the following simple loop:
A - > B -> D
A -> C -> D

You can define two lineages like that, where cells are shared both at the beginning and at the end of the lineages. Finding branch assignment might be tricky with a general code but I will try to work on something to help you.

Also I am quite skeptical of those loops appearing in the plot above and whether they really represent meaningful biology. In my experience, those - and the very short branches - are not real. You can at least quite easily delete the laters by changing the `minimal_branch_len` argument in the `learn_graph` function.

**Comment by kathrynbowles** [comment] 2020-04-19 18:28
Hi @HectorRDB, 

Thanks, I'd missed those. I'll try changing my learn graph parameters to get a loop-less graph then calculate the weights again.

**Comment by HectorRDB** [comment] 2020-04-20 08:56
Great, please keep me posted.

**Comment by kathrynbowles** [comment] 2020-04-21 16:36
Hi @HectorRDB - so far so good. I re-ran `learn_graph` with `close_loop = FALSE`, which generated trajectories without any loops. The fitGAM didn't throw the same error, and has now been running for ~24h, but with the number of cells I have I think it will take a while. 

Thanks for your help!

**Comment by HectorRDB** [comment] 2020-04-21 17:19
Hi @kathrynbowles ,
Great to hear. 
I would recommend running first on a few genes to make sure everything is working well. 
I will close the issue. If something else pops up, you are more than welcome to open another one so we can work out issues.
Best

**Closed by HectorRDB** 2020-04-21 17:19 UTC

**Comment by TinaGuo-hku** [comment] 2022-12-13 18:02
Hi @HectorRDB  
I have the same issue that around 1/3 of cells have 0 weights. I rerun the learn_graph to make sure there's no loop but the issue's still here. 
Could you please help me to take a look?
<img width="491" alt="Screen Shot 2022-12-13 at 1 02 19 PM" src="https://user-images.githubusercontent.com/74233095/207410222-86b69cf0-53e8-4945-9853-8278a89e515f.png">

**Comment by TinaGuo-hku** [comment] 2022-12-13 19:50
Hi @HectorRDB, I realized following code only works for the case where there's only one root, if we have multiple roots, igraph::shortest_paths(mst, root, endpoint)$vpath[[1]] only takes in the first element of root, which eventually results in 0 weight for some cells ( correct me if I am wrong)
root <-cds@principal_graph_aux$UMAP$root_pr_nodes
cellWeights <- lapply(endpoints, function(endpoint) {
  # We find the path between the endpoint and the root
  path <- igraph::shortest_paths(mst, root, endpoint)$vpath[[1]]
  path <- as.character(path)
  # We find the cells that map along that path
  df <- y_to_cells %>%
    dplyr::filter(Y %in% path)
  df <- data.frame(weights = as.numeric(colnames(cds) %in% df$cells))
  colnames(df) <- endpoint
  return(df)
  })

**Comment by Kenneth-new-user** [comment] 2023-09-20 09:54
Despite having only 1 root and no loops in the graph, I am still getting the error:

Error in .assignCells(cellWeights) :
Some cells have no positive cell weights.

When trying to generate an sce object from Monocle3 data.
