### ISSUE TITLE
Error with plotGeneCount()

### ISSUE THREAD

**Issue by aditisk** [statOmics/tradeSeq#12] opened 2019-08-26 16:06 UTC
I am trying to run the steps as shown in the vignette. When I reach the plotGeneCount() function in the "Discovering progenitor marker genes" section I get this error:

> plotGeneCount(crv, counts=counts, gene = sigGeneStart)
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘structure("SlingshotDataSet", package = "slingshot")’ to a data.frame

The same thing is happening in the subsequent uses of this function too. Could you please help me figure out what Is going wrong  and how I can fix it ?

Thanks.

**Comment by koenvandenberge** [comment] 2019-08-26 16:22
Thank you for letting us know. However, I cannot reproduce this error with the latest version of `tradeSeq` (version 0.99.44). 

Are you using the same data as in the vignette?
If you're not using the latest `tradeSeq` version, could you try reinstalling?

**Comment by koenvandenberge** [comment] 2019-08-27 09:59
Could you share your code, starting with the Slingshot trajectory fitting up to the error?

**Comment by koenvandenberge** [comment] 2019-08-27 12:25
Many thanks for providing this, I think we're getting closer to the issue.

How many lineages does Slingshot discover? This can be checked by printing the output of `crv`.

Can you also share the output from `gamList[[1]]$smooth[[1]]$xp`?

**Comment by koenvandenberge** [comment] 2019-08-27 13:31
Great, thanks. I didn't see anything wrong in your output so I digged into the `plotGeneCount` function and found that it was only implemented for a maximum of two lineages. The latest version now allows for any number of lineages. It would be great if you could re-install tradeSeq and check if it works now.

Thanks for bringing this to our attention.

**Comment by koenvandenberge** [comment] 2019-08-27 15:11
Did you re-install tradeSeq in the same R session you've loaded it in? This is not a tradeSeq issue and I guess it should be fixed when restarting R.

**Closed as completed** 2019-08-27 16:13 UTC
