### ISSUE TITLE
Running only one lineage

### ISSUE THREAD

**Issue by jportman92** [statOmics/tradeSeq#187] opened 2022-04-08 15:47 UTC
Hi,

Thank you for developing this amazing package. I have a Pseudotime Object from slingshot that has 7 lineages. I initial attempted to run the `fitGAM` function on this object with a condition with two factors (WT and Mutant). Example below.
```
sds <- slingshot(Embeddings(seurat, "umap"), clusterLabels = seurat$seurat_clusters, 
                 start.clus = 0)
counts <- as.matrix(seurat@assays$RNA@counts)
fitGAM(counts = counts, sds, conditions = factor(seurat$condition),
              nknots = 8)
```

I quickly realised that this would take a large amount of time to run with the amount of computations needed, and implementing parallelisation did not significantly look to speed up the process. However, of them 7 lineages I am only interested in one or two, with the main focus to see what genes are deferentially expressed between the two conditions across those specific pseudotimes. When attempting to subset the pseudotime and cell weight vectors I ran into the following warning

```
pseudotime <- slingPseudotime(sds, na=FALSE)
weight <- slingCurveWeights(sds)
sce <- fitGAM(counts = counts, pseudotime = pseudotime[,1],
              cellWeights = weight[,1],
              conditions = factor(seurat$condition),
              nknots = 8, genes = 1:10)
Fitting lineages with multiple conditions. This method has been tested on a couple of datasets, but is still in an experimental phase.
Error in .assignCells(cellWeights) : 
  Some cells have no positive cell weights.
```

I therefore wondered if the following piece of code would be valid to circumvent this and only run one lineage? I have removed all cells that have a NA value for the specific pseudotime. Then subset the counts matrix, cell weights and condition vector to contain only the cells present.
```
counts <- as.matrix(seurat@assays$RNA@counts)
pseudotime <- slingPseudotime(sds)
lineage_pseudotime  <- na.omit(slingPseudotime(sds))[,1]
weight <- slingCurveWeights(sds)[names(lineage_pseuodtime), 1]
sce <- fitGAM(counts = counts[,names(lineage_pseuodtime)], pseudotime = lineage_pseudotime,
              cellWeights = weight,
              conditions = factor(seurat$condition[names(lineage_pseuodtime)]),
              nknots = 8, genes = 1:10)
```

Apologies if this has previously been answered and I have missed the relevant post.

**Comment by koenvandenberge** [comment] 2022-04-11 15:25
Hi @jportman92,

Thank you for posting, this is a great question.
One option would be to select all cells with non-zero assignment to your two lineages of interest, as below.

```
pseudotime <- slingPseudotime(sds, na=FALSE)
cellWeights <- slingCurveWeights(sds)
lineagesOfInterest <- 1:2 # replace by the lineage(s) you're interested in.
relevantCells <- rowSums(cellWeights[,lineagesOfInterest]) > 0 # use these cells
sce <- fitGAM(counts = counts[,relevantCells], 
              pseudotime = pseudotime[relevantCells,],
              cellWeights = cellWeights[relevantCells,],
              conditions = factor(seurat$condition[names(lineage_pseuodtime)][relevantCells]))
```

However, this means that if a particular cell has a weight of `0.01` to lineage 2 and a weight of `0.99` to lineage 3, it will be assigned to lineage 2, if we use this code. This is because it will be included in the `relevantCells` vector (as it has a non-zero weight for lineage 1 and/or 2), and in the downstream `fitGAM` code where we focus on the first two lineages, lineage 2 will be the only lineage for which it has a non-zero weight and thus to which it will be assigned. If using this approach, you therefore may want to explore a reasonable threshold to use for selecting relevant cells.

The other option is to try fitting the model for all cells and all seven lineages. To speed things up, you may consider also selecting a subset of genes, using [a feature selection method](http://bioconductor.org/books/3.13/OSCA.basic/feature-selection.html). 

While the former may seem a suboptimal approach due to cell assignment issue, the latter will result in a model that will be much harder to fit: you are trying to fit 7 lineages * 2 conditions * 8 knots =  112 regression coefficients per gene! You may consider reducing the number of knots to, e.g., 5 to partially help with this, as well as checking whether the trajectory has not been overfitted.  And, as above, reducing the number of genes you are trying to fit would also help in lowering the computational burden.

Hope this helps.

**Comment by jportman92** [comment] 2022-04-12 16:37
Hi @koenvandenberge 

That is very helpful, thank you for your quick an extensive reply.
I agree that I feel there is some over-fitting, especially with lineages extending to "satellite" clusters and it is something I am looking to discuss with the collaborators and hopefully rectify. I had thought about the first approach to have an initial look at one of the lineages I was confident had existing biological proof, and I can see how the former approach you mention could be useful for quicker investigations, but fully agree, the latter would be much more appropriate to provide more confidence in the end result and is the method I am going to strive to accomplish. 

I do have a follow up question if that's OK. With this analysis I also had the same issue as stated in #121.
```
Impossible to place a knot at all endpoints.Increase the number of knots to avoid this issue.
```
I managed to get a series of plots from `evaluateK` to be produced with trialling a few ranges of K, and from these settled on 8 knots, albeit still with the same warning. 
I followed the advise from @HectorRDB and continued with caution. 
My question therefore is, is it reasonable to decided on a number of Knots with these multiple factors, i.e variance and speed, in mind? For example, choosing the most optimal number of Knots that would not require large amounts of computation.
Or would you say it would be better to tweak the genes, and potentially the number of lineages first (however in a perfect example we would be considering data in which all the lineages are relevant) before looking at changing the number of Knots?
However, I appreciate this might be a more abstract question depending on what is valued more. 

All the best, and thank you again for you help and advice.

**Comment by koenvandenberge** [comment] 2022-04-13 09:28
Hi @jportman92 

The message about the knots is not a warning, it is just a message to let you know that we are deviating from our default implementation. In your setting, this is not unsurprising as you had specified 8 knots and had 7 lineages. So if you would want to have knots at all endpoints you'd have one knot at pseudotime=0 and the other 7 knots would be reserved for each of the 7 endpoints of your lineages, which is unlikely to be a good idea in terms of your spreading of knots. It is therefore not exceptional to see this message. 

In our benchmarks, we see little effect of varying the number of knots in terms of the results of the statistical inference (eg number of DE genes using one of the tests), as long as you use a reasonable number of knots (at least 4 or 5, I would say). So I would not focus too much on trying to tweak the number of knots.

**Comment by jportman92** [comment] 2022-04-14 08:33
Hi @koenvandenberge 

Thank you for clearing up my misinterpretation and your advice regarding the number of knots.
Also thank you for taking the time to answer these questions, its greatly appreciated and helps a lot.

All the best

**Comment by koenvandenberge** [comment] 2022-04-14 10:03
Glad you found it helpful! Let us know if any other questions pop up.

**Closed by koenvandenberge** 2022-04-14 10:03 UTC
