### ISSUE TITLE
Differential test on two conditions within the same slingshot trajectory?

### ISSUE THREAD

**Issue by jeremymsimon** [statOmics/tradeSeq#19] opened 2019-11-08 20:19 UTC
We have a trajectory of single cells generated by slingshot, but the cells are mixed from two conditions (mutant, wild-type)--in other words, we have one unified slingshot object and one trajectory of interest within it. We see some differences along pseudotime of that unified trajectory, suggestive of some kind of developmental shift due to genotype. What we'd like to do is run tradeSeq to call genes that are differentially expressed along this lineage, but it seems the vignette mainly describes calling differences across two independent lineages. 

Is there a way to subset the slingshot object and/or read the data into tradeSeq such that we can compare expression of WT cells to mutant cells along the same pseudotime axis? 

Thanks!

**Comment by koenvandenberge** [comment] 2019-11-08 20:30
Hi @jeremymsimon 

Just to see if I understand the question: you are interested in comparing gene expression between two conditions within a single lineage of the trajectory?
This is currently not implemented in `tradeSeq`, but it seems like an interesting extension, though. Would you be willing to share the data with us to look into it?

Best,
Koen

**Comment by jeremymsimon** [comment] 2019-11-08 20:33
Yes, precisely. We didn't want to generate separate trajectories for each genotype, so this way we get one picture of overall differentiation, and then can compare the genotypes within that.

I'd be happy to share some data your way, but we're also willing to try a more hack solution if you can think of one. What sort of files and metadata would you need?

**Comment by koenvandenberge** [comment] 2019-11-08 20:51
Cool.
If you could share the count matrix, Slingshot object and metadata telling us which cell belongs to which condition, we should be able to get started, I think. My email is koen.vandenberge@ugent.be.

There's some hacky solutions that could be worthwhile if you'd want to get quick results to get you going, e.g. treating each condition within a lineage as a separate lineage in `tradeSeq` and performing DE between them (i.e., making the `lineage*condition` interaction explicit). Haven't tried any of this yet, though.

**Comment by jeremymsimon** [comment] 2019-11-08 20:56
Okay we will package that up and send it your way ASAP. Thanks!

One other (_very_) hack idea we had was to add a large value to, say, just the UMAP2 coordinates of one of the genotypes, then run slingshot specifying one start position per genotype. That way we (should) get 2 trajectories (one per genotype) and then could compare them in tradeSeq. This is far from a publishable solution but might at least give us a cursory glance at what the result may look like...

**Comment by koenvandenberge** [comment] 2019-11-08 21:20
Could work, but you might run into the issue that the lineages get out-of-sync due to different pseudotimes because of the offset you've added, unless you think hard about the offset you'll add.
One thing @kstreet13 and I have been thinking about is quantifying abundance of different conditions along lineages. It is not yet per gene, but you might find it useful nonetheless: https://bioconductor.org/packages/release/bioc/vignettes/slingshot/inst/doc/conditionsVignette.html

**Comment by jeremymsimon** [comment] 2019-11-11 15:24
Yes @kstreet13 and I interacted on the slingshot repo about that exact problem too, actually, because we not only have a difference in abundance of cells between conditions at certain points along the trajectory, but also (likely) differential expression!

We will package up some data for you and send it your way in the next day or two. Thanks!

**Comment by Seandelao** [comment] 2020-04-29 21:39
Hi @koenvandenberge, 

I was wondering what the status of this capability is? I have a merged dataset that I think would be very interesting to do a within-lineage comparison on based off of a certain condition. 

I see that there is a condition branch on the Github page, but I will be the first to admit that I am not the best at navigating the relevant code from Github/a novice R user... 

Thank you!

**Comment by koenvandenberge** [comment] 2020-04-29 23:01
Hi,

We are still developing it and I can therefore not guarantee it will work like a charm, but if you are interested, you are welcome to try it out. Please do let us know if/how it works for you since we haven't done a lot of testing yet.

You can install the branch using `devtools::install_github("statOmics/tradeSeq", ref="conditions")` and to do a within-lineage comparison, you fit the models using `fitGAM` where you'll have an additional argument called `conditions` which expects a factor variable for the conditions. Then you could use the `conditionTest` function to test for DE between conditions within a lineage. The results of this test can be interpreted as results from the `patternTest`, i.e. it checks for differentially expressed patterns between the smoothers from each of the conditions.

**Comment by Seandelao** [comment] 2020-04-30 02:27
@koenvandenberge thanks for the response! 

Is the "conditions" argument for like a matrix, where you would have each cell as the rownames, and the condition as a column?

**Comment by koenvandenberge** [comment] 2020-04-30 02:29
It should be a vector of class factor, where the length of the vector is equal to the number of columns (cells) of your count matrix.

For example
`conditions = factor(rep(c("control", "treatment"), each=50))`

**Comment by Seandelao** [comment] 2020-04-30 02:34
Got it. 
If I am running:

sce <- fitGAM(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights,
                 nknots = 6, verbose = FALSE, conditions = factor(rep(c("control", "treatment"), each=50)))

where is the identifier for each cell as to which condition it belongs to? I know in something like a Monocle object it would be in the column data, but in this case I would be running fitGAM off of a count matrix with cells in the columns and genes in the rows.... 

Sorry if this is a simple question/obvious answer!

**Comment by Seandelao** [comment] 2020-04-30 15:49
@HectorRDB @koenvandenberge  got it, thank you! Will try it out and let you know how it goes.

**Comment by Seandelao** [comment] 2020-04-30 23:23
@HectorRDB @koenvandenberge what about in the case of using Slingshot on a Seurat object?

I am getting my lineages by using Slingshot as follows: 

slingshot <- slingshot(Embeddings(Human_InVitro_Merge_Alpha_Beta, "umap"), 
                       clusterLabels = Human_InVitro_Merge_Alpha_Beta$seurat_clusters, 
                       start.clus = "4",
                       end.clus = c("2", "0"),
                       stretch = 0)

Which, after extracting pseudotime, etc. I then tried running the following: 

sce <- fitGAM(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights,
              nknots = 6, verbose = FALSE, conditions = Human_InVitro_Merge_Alpha$type)

where "type" is a column in the Seurat object meta data designating if each cell comes from in vitro or in vivo means. 

However, I got the error: 
Error in .local(counts, ...) : conditions must be a factor vector

**Comment by koenvandenberge** [comment] 2020-05-01 01:34
Hi @Seandelao 
The error should be clear: the `conditions` vector must be a factor vector.
You could try 
```
sce <- fitGAM(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights,
nknots = 6, verbose = FALSE, conditions =as.factor(Human_InVitro_Merge_Alpha$type))
```
to see if that fixes it.

**Comment by Seandelao** [comment] 2020-05-01 17:07
Hi @koenvandenberge, 

Thanks for the suggestion, that worked. 

I ran the fitGAM on a single lineage with the condition and it ran to ~6% finished until it produced this error: 

Error in gam.fit4(x, y, sp, Eb, UrS = UrS, weights = weights, start = start,  : 
  inner loop 3; can't correct step size

Is this due to something with the number of knots selected? I used a few different numbers, but nknots = 3 ran the longest before producing the error.

**Comment by koenvandenberge** [comment] 2020-05-04 05:39
Hi @Seandelao 

This is related to the error handling that got updated in `fitGAM` but didn't seem to catch all errors from `mgcv`. I updated the software now, could you please check again if it works for you with the latest version?

Thanks.

**Comment by Seandelao** [comment] 2020-05-04 18:07
Hi @koenvandenberge, I am still getting the same error after re-installing the "conditions" branch.

**Comment by koenvandenberge** [comment] 2020-05-05 05:01
Thanks @Seandelao, this was my bad, I forgot that you're working on the `conditions` branch. I will integrate the changes there soon and will let you know when it happened.

**Comment by Seandelao** [comment] 2020-05-05 17:24
@koenvandenberge no worries, thanks!

**Comment by koenvandenberge** [comment] 2020-05-07 18:27
Hi @Seandelao we have now merged the updates in `master` in the `conditions` branch. It would be great if you could check whether your problem still persists. Thanks.

**Comment by Seandelao** [comment] 2020-05-08 02:54
Thanks @koenvandenberge!

I ran: 
sce <- fitGAM(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights,
              nknots = 4, verbose = TRUE, conditions =as.factor(Human_InVitro_Merge_Beta$type))

which ran all of the way through. However, when I try to run: 
conditionTest(sce)

I get the error: 
Error in .conditionTest(models = models, global = global, pairwise = pairwise,  : 
  You cannot run this test with only one lineage.

If I also run the PlotSmoothers, it only plots one lineage.

**Comment by koenvandenberge** [comment] 2020-05-12 21:55
Hi @Seandelao 
My apologies for the delay in getting back to you. I just tried this on another dataset with only a single lineage and 2 conditions, where it works.  Do you mind sharing object you got after running `fitGAM` so we can figure out what might be happening?
If you need an e-mail, please send to koenvdberge@berkeley.edu

**Comment by Seandelao** [comment] 2020-05-13 16:51
Hi @koenvandenberge 
No worries! Just shot you an email.

**Comment by koenvandenberge** [comment] 2020-05-15 17:31
Hey @Seandelao 
I just took a look at your `tradeSeq` object but it looks to me like it was fitted without the `conditions` argument, which explains the error. Could that be true?

**Comment by Seandelao** [comment] 2020-05-15 17:38
Hi @koenvandenberge, I definitely used the condition argument: 

sce <- fitGAM(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights,
nknots = 4, verbose = TRUE, conditions =as.factor(Human_InVitro_Merge_Beta$type))

I can try running again and seeing if I get the same result?

**Comment by koenvandenberge** [comment] 2020-05-15 17:46
Can you share the output of `table(as.factor(Human_InVitro_Merge_Beta$type))`?

The output does not show that the `conditions` argument had been used. It might be worth to try again, first re-installing through `devtools::install_github("statOmics/tradeSeq", ref="conditions")`, restarting `R` before you load `tradeSeq` again, and then refitting, just to be sure.
If that still gives the same issue I can take a look at it if you share the inputs to `fitGAM`.

**Comment by Seandelao** [comment] 2020-05-15 19:21
@koenvandenberge the output is:
In_Vitro  In_Vivo 
    2828     7683 
I'll re-install, restart and re-run and let you know how it goes!

**Comment by Seandelao** [comment] 2020-05-16 03:11
Hi @koenvandenberge, running the function produced a single lineage (meaning no condition). 
I've just sent a link to all of the items.

**Comment by koenvandenberge** [comment] 2020-05-17 02:30
Hi @Seandelao 
The conditions branch has now been updated; some changes had inadvertently been reversed during one of the merges with the master branch. I tried running a subset of your data and it ran successful for me.

**Comment by Seandelao** [comment] 2020-05-17 17:51
Hi @koenvandenberge, 
Thanks, just used it and it worked!
However, I am now getting an error I haven't seen before when using the PlotSmoothers function: 

plotSmoothers(sce, counts = counts, gene = "INS")
Error in if (dm[ii, paste0("l", jj)] == 1) { : argument is of length zero

**Comment by koenvandenberge** [comment] 2020-05-17 20:50
We are still working on extending `plotSmoothers` for the multiple condition case. There is one way which is not very elegant but it could do the job for now: `tradeSeq:::.plotSmoothers_conditions(sce, counts = counts, gene = "INS")`. I will let you know as soon as we've finished updating `plotSmoothers`.

**Comment by Seandelao** [comment] 2020-05-17 22:40
That works, thank you!

**Comment by koenvandenberge** [comment] 2020-05-21 00:51
@Seandelao `plotSmoothers` should now work for multiple conditions.

**Comment by Seandelao** [comment] 2020-05-21 18:14
@koenvandenberge thanks, it works for me!

**Comment by liuyigh** [comment] 2020-06-07 17:34
Hi, I would like to put my `conditions` issues here in one thread. Hope you don't mind.

I got this with .fitGAM() using two workers.
```
Error in names(res) <- nms : 
  'names' attribute [16942] must be the same length as the vector [11094]
```
16942 is number of genes, while 11094 is number of cells. It seems there is transpose missing? And I have genes in rows and cells in columns as required for `counts`. If I transpose that, it even won't allow me to do .fitGAM()

I could not find any code `names(res) <- nms` in `tradeseq` though. It may be some incompatibility with other packages?

**Comment by koenvandenberge** [comment] 2020-06-09 02:46
Hi @liuyigh 

See issue #43 , this is an issue with parallelization.
It is currently unknown what exactly is causing this issue but it is related to `BiocParallel`, I think. I ran into it myself, and when I restarted running it would sometimes work, other times not. So I suggest either re-evaluating the code, or running without parallelization.

**Comment by liuyigh** [comment] 2020-06-09 06:38
Thanks! Sorry that I did not catch the previous issue report.

I went again without parallelization. Then got this error:

```
the condition has length > 1 and only the first element will be usedToo many cells seem to be squeezed at one pseudotime value, the smoothers will work with evenly spaced knots instead of quantile-based knots. Interpret results with caution. Increase the number of knots to avoid this issueImpossible to place a knot at all endpoints.Increase the number of knots to avoid this issue.
```

i was using 6, then 24 knots, tried 36 knots. Same error. 

Let me know if I am harassing you too much. I understand you are providing this for free, not a service.

**Comment by koenvandenberge** [comment] 2020-06-09 15:24
No worries, you should not be encountering these errors and it is informative for us so we can make the software better.
Do you mind sharing (subset of) the data that reproduces this error?

Do you have a visualization of the trajectory you are looking at? The knots warning typically happens when cells are unbalanced along a lineage, or you have many lineages.

**Comment by liuyigh** [comment] 2020-06-27 05:20
> Do you mind sharing (subset of) the data that reproduces this error?
I have just emailed data to your Berkeley email.
 
> Do you have a visualization of the trajectory you are looking at? The knots warning typically happens when cells are Unbalanced along a lineage, or you have many lineages.

A visualization of the trajectory is attached below. Indeed, I have 4 lineages and they are not balanced.

![000011](https://user-images.githubusercontent.com/5641850/85915286-03675780-b7fb-11ea-89ac-cbe3a1a0ea2c.png)

**Comment by koenvandenberge** [comment] 2020-06-30 16:43
Hi @liuyigh 

I took a look at your dataset and it seems like you're using counts that have been scaled by `Seurat` in some way, containing many negative values.

How far into the fitting were you seeing this error? 
Following the code you e-mailed me, I am fitting the first couple of genes in you dataset using the code below, which seems to work for me.

```
countsIk <- round(as.matrix(dcSubReg@assays$RNA@counts))
sce <- fitGAM(counts = countsIk, 
              sds=sds,
              nknots = 6, 
              conditions = conditions2, 
              parallel=FALSE)
```

**Comment by liuyigh** [comment] 2020-07-29 05:47
Hi @koenvandenberge 

I used raw counts, disabled parallel and reduced genes to a few hundreds, and it fitted in 2 hours. Hooray,

I have two things to report:
1.  I have 4 lineages and two conditions wt and ko
`yhatSmooth <- predictSmooth(sce, gene = conditionGenes, nPoints = 50, tidy = FALSE)`

produced colnames like this. Not sorted by lineage or conditions.
```
 [1] "lineage1_conditionwt_point1"  "lineage2_conditionwt_point2"  "lineage3_conditionwt_point3"  "lineage4_conditionwt_point4" 
  [5] "lineage1_conditionko_point5"  "lineage2_conditionko_point6"  "lineage3_conditionko_point7"  "lineage4_conditionko_point8" 
  [9] "lineage1_conditionwt_point9"  "lineage2_conditionwt_point10" "lineage3_conditionwt_point11" "lineage4_conditionwt_point12"
 [13] "lineage1_conditionko_point13" "lineage2_conditionko_point14" "lineage3_conditionko_point15" "lineage4_conditionko_point16"
 [17] "lineage1_conditionwt_point17" "lineage2_conditionwt_point18" "lineage3_conditionwt_point19" "lineage4_conditionwt_point20"
 [21] "lineage1_conditionko_point21" "lineage2_conditionko_point22" "lineage3_conditionko_point23" "lineage4_conditionko_point24"
 [25] "lineage1_conditionwt_point25" "lineage2_conditionwt_point26" "lineage3_conditionwt_point27" "lineage4_conditionwt_point28"
 [29] "lineage1_conditionko_point29" "lineage2_conditionko_point30" "lineage3_conditionko_point31" "lineage4_conditionko_point32"
 [33] "lineage1_conditionwt_point33" "lineage2_conditionwt_point34" "lineage3_conditionwt_point35" "lineage4_conditionwt_point36"
 [37] "lineage1_conditionko_point37" "lineage2_conditionko_point38" "lineage3_conditionko_point39" "lineage4_conditionko_point40"
 [41] "lineage1_conditionwt_point41" "lineage2_conditionwt_point42" "lineage3_conditionwt_point43" "lineage4_conditionwt_point44"
 [45] "lineage1_conditionko_point45" "lineage2_conditionko_point46" "lineage3_conditionko_point47" "lineage4_conditionko_point48"
 [49] "lineage1_conditionwt_point49" "lineage2_conditionwt_point50" "lineage3_conditionwt_point1"  "lineage4_conditionwt_point2" 
...
```
2. my conditions are factors:
`conditions <- factor(seurat$genotype, levels=c('wt','ko'))`

I found the plotSmoother() curves have wt and ko flipped in all lineages. Do you know why?

**Comment by liuyigh** [comment] 2020-08-11 18:19
One more suggestion, it would be great if `conditionTest()` can tell the direction of difference, or which condition is higher, which is lower. Currently up and down regulated genes are mixed together.

One option is to return `estFC` from `getEigenStatGAMFC()`

**Comment by koenvandenberge** [comment] 2020-08-12 16:01
Hi @liuyigh 

The names got mixed up for `predictSmooth` in the `conditions` branch and this has now been fixed, thank you for letting us know. 
We will be working on effect sizes or directions for the `conditionTest`. Note that, since the fold changes may be positive or negative depending on the pseudotime, it is not immediately clear what would be the most informative to return here.

**Comment by cstrlln** [comment] 2020-09-09 23:01
Hi I did the install of the conditions branch but getting an error when trying to run it

Interestingly when I run this goes without problem:

icMat <- evaluateK(counts = as.matrix(assays(sce_pc4_sling)$counts), sds = sds, conditions = colData(sce_pc4_sling)$Condition, k = 3:10, 
                   nGenes = 200, verbose = T)

but when I move to this:

sce_pc5 <- fitGAM(counts = as.matrix(assays(sce_pc4_sling)$counts), sds = sds, conditions = factor(colData(sce_pc4_sling)$Condition), nknots = 5, verbose = T)
 
I get this error:

Error in .local(counts, ...) : 
  unused argument (conditions = c(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 


Any advice?
thanks

**Comment by koenvandenberge** [comment] 2020-09-09 23:05
Hi @cstrlln 

Could you please let us know which version you are working with? This is an issue that looks like something we've had before so it may already have been fixed with the latest version. 
It would be great if you could check that, since our automatic testing of the most recent branch seems to run without (known) issues.

**Comment by cstrlln** [comment] 2020-09-09 23:11
I just did this today actually, as per the discussion above:
devtools::install_github("statOmics/tradeSeq", ref="conditions")

> packageVersion('tradeSeq')
[1] ‘1.3.14’

**Comment by cstrlln** [comment] 2020-09-10 03:21
Correction: just ran it in a different computer and went through. 
I will try again in the computer that failed but was probably a package installation issue. 
In the new computer I got an error while installing tradeSeq from github that, after some googling, pointed me to restart R and reinstall the package. After this it worked fine.
Thank you for the fast response!

**Comment by koenvandenberge** [comment] 2020-09-10 03:25
Great, thank you for letting us know. Feel free to reach out if any additional questions pop up.

**Comment by liuyigh** [comment] 2020-10-26 04:41
Dear Koen and authors,

One more question, 

is it possible to run pairwise `patternTest()` between lineages _within_ conditions, respectively? For example, lineage 1 v. lineage 4 within WT and KO. I assume I can subset the seurat dataset and run `tradeseq` `fitGAM()` separately. 

Is it possible for me to use the existing `sce` object I have already fitted `fitGAM()`? 

May I subset the `sce` by condition then run `patternTest()`?

Thanks!
-- Yi

**Comment by koenvandenberge** [comment] 2020-12-18 14:42
Hi @liuyigh 

Sorry, I must have forgotten about this question.
We currently do not have functionality where within-condition between-lineage comparisons are possible given the fitted GAM across all lineages and all conditions. You could indeed subset by condition and run the pipeline for each condition.

**Comment by HectorRDB** [comment] 2021-01-05 16:54
Given that this is now the full version of `tradeSeq` and not just a branch, I will close that issue and let users open another one if (when?) needed

**Closed by HectorRDB** 2021-01-05 16:54 UTC
